# Generated by Django 3.2.2 on 2023-07-10 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('BS ComputerScience', 'BS ComputerScience'), ('BS Physics', 'BS Physics'), ('BS English', 'BS English'), ('BS Political Science', 'BS Political Science')], default='BS ComputerScience', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('GDC TAKHTBHAI', 'GDC TAKHTBHAI'), ('GDC MARDAN', 'GDC MARDAN')], max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 11 digits allowed.', regex='^\\d{11,11}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('student', 'student'), ('Portal Managing', 'Portal Managing')], default='student', max_length=20),
        ),
    ]
